Converted to es6 classes/modules and added imports
adaptlearning/adapt-contrib-resources pull request #68
Opened 2021-06-15 15:25 UTC by eleanor-heath

2021-06-15 16:13 UTC, oliverfoster requested changes

2021-06-15 16:13 UTC, oliverfoster commented on js/ResourcesView.js
> +export default class ResourcesView extends Backbone.View {
```suggestion
import Adapt from 'core/js/adapt';

export default class ResourcesView extends Backbone.View {
```

Add line to differentiate between import and export statements.

2021-06-15 16:13 UTC, oliverfoster commented on js/ResourcesHelpers.js
> +class ResourcesHelpers {
This should be left as an `Object` as it never needs to be instantiated, it's just acting as "hash" / a named list for a loop.

2021-06-15 16:13 UTC, oliverfoster commented on js/adapt-contrib-resources.js
> +class Resources {
What we've tended to do with these kind of controller classes is make them into a singleton.

https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/headings.js#L17

The class inherits the ability to be an event listener from `Backbone.Controller` and its `initialize` function is executed when the `Backbone.Controller` is instantiated. At the end of the file the singleton is instantiated and returned.

2021-06-16 08:25 UTC, oliverfoster requested changes

2021-06-16 08:25 UTC, oliverfoster commented on js/adapt-contrib-resources.js
> +    this.listenTo(Adapt, 'adapt:start', this.initResources);
Could you also change 
` Adapt.on('resources:showResources', () => {`
to:
`this.listenTo(Adapt, 'resources:showResources', () => {`

2021-06-16 08:25 UTC, oliverfoster commented on js/ResourcesHelpers.js
> +define([
These should still be imports.

2021-06-16 08:25 UTC, oliverfoster commented on js/ResourcesHelpers.js
> -export default ResourcesHelpers;
`export default helpers;` should suffice here

2021-06-16 08:39 UTC, oliverfoster approved these changes

2021-06-16 08:40 UTC, oliverfoster commented
Oh, can you put the package.json back please?

2021-06-16 08:51 UTC, oliverfoster approved these changes

2021-06-18 08:22 UTC, cahirodoherty-learningpool approved these changes
👀

2021-06-21 11:42 UTC, ethan-lp approved these changes
👀

2021-06-22 08:26 UTC, merged